version: '3'

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    ports:
      - 3306:3306
    networks:
      - springmysql-net
  app_achat_back:
    image : ahmedazizelj/achat_back
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - 8089:8089
    networks:
      - springmysql-net
      - frontend
  app_achat_front :
    image : ahmedazizelj/achat_front
    ports:
      - 4200:80
    links :
      - app_achat_back
    restart : on-failure
    networks :
      - frontend
networks:
  springmysql-net:
  frontend: